version: '3.8'

services:
  app:
    build:
      context: .
    links:
      - db
    ports:
      - '8000:8000'
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
      - ./log.txt:/app/log.txt
    
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
