version: '3.8'

services:
  app:
    build:
      context: .
    links:
      - db
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - ./log.txt:/app/log.txt
    
  db:
    image: postgres:15.2-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
