basePath: /
definitions:
  Effective-Mobile_internal_structures.Car:
    properties:
      id:
        example: 1
        type: integer
      mark:
        example: BMW
        type: string
      model:
        example: X5
        type: string
      owner_id:
        example: 1
        type: integer
      regnum:
        example: A111AA155
        type: string
      year:
        example: 2015
        type: integer
    type: object
  Effective-Mobile_internal_structures.Owner:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: Max
        type: string
      patronymic:
        example: Olegovich
        type: string
      surname:
        example: Shestakov
        type: string
    type: object
  Effective-Mobile_internal_structures.StatusBadRequestMessage:
    properties:
      message:
        example: 'Error: bad request'
        type: string
    type: object
  Effective-Mobile_internal_structures.StatusInternalServerErrorMessage:
    properties:
      message:
        example: 'Error: internal server error'
        type: string
    type: object
  Effective-Mobile_internal_structures.StatusNotFoundMessage:
    properties:
      message:
        example: 'Error: not found'
        type: string
    type: object
  Effective-Mobile_internal_structures.StatusOKMessage:
    properties:
      status:
        example: ok
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a RESTful API for Effective-Mobile project
  title: Effective-Mobile API
  version: "1.0"
paths:
  /cars:
    post:
      consumes:
      - application/json
      description: Add a new car to the database from JSON input.
      operationId: create-car
      parameters:
      - description: Car info (only regnum, mark, model, year and owner_id are required).
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/Effective-Mobile_internal_structures.Car'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusOKMessage'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusBadRequestMessage'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusNotFoundMessage'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusInternalServerErrorMessage'
      summary: Create car
      tags:
      - API Functions
  /cars/{id}:
    delete:
      consumes:
      - application/json
      description: Delete car from database by id.
      operationId: delete-car
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusOKMessage'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusBadRequestMessage'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusNotFoundMessage'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusInternalServerErrorMessage'
      summary: Delete car
      tags:
      - API Functions
    put:
      consumes:
      - application/json
      description: Update car info in the database by id.
      operationId: update-car
      parameters:
      - description: Car info to update (only regnum, mark, model, year and owner_id
          are required).
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/Effective-Mobile_internal_structures.Car'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusOKMessage'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusBadRequestMessage'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusNotFoundMessage'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusInternalServerErrorMessage'
      summary: Update car
      tags:
      - API Functions
  /info:
    get:
      consumes:
      - application/json
      description: Get all cars from database or filtered by regnum, mark and model
        (optional).
      operationId: get-all-cars
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusOKMessage'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusBadRequestMessage'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusNotFoundMessage'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusInternalServerErrorMessage'
      summary: Get cars
      tags:
      - API Functions
  /owners:
    post:
      consumes:
      - application/json
      description: Add a new owner to the database from JSON input.
      operationId: add-owner
      parameters:
      - description: Owner info (only name, surname are required).
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/Effective-Mobile_internal_structures.Owner'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusOKMessage'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusBadRequestMessage'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusNotFoundMessage'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/Effective-Mobile_internal_structures.StatusInternalServerErrorMessage'
      summary: Add owner
      tags:
      - API Functions
swagger: "2.0"
